config/routes.rb
Rails.application.routes.draw do
  get 'courses/index'

  get 'greeter/hello'
  get 'greeter/goodbye'

  root 'courses#index'
  #get 'greeter/about' => 'greeter#hello' This will rout about to greeter controller and hello action
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coursera.rb
class Coursera
	include HTTParty

	base_uri 'https://api.coursera.org/api/courses.v1'
	default_params fields: "photoUrl,description" , q: "search"
	format :json

	def self.for term
		get("",query: {query: term}, verify: false)["elements"]
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
  	@search_term = params[:looking_for] || 'jhu'
  	@courses = Coursera.for(@search_term)
  end
end

app/controllers/greeter_controller.rb
class GreeterController < ApplicationController
  def hello
    @random_name = ["Dipayan","Nishant","Gopal"]
    @name = @random_name.sample
    @time = Time.now
  end
  def goodbye
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/greeter_helper.rb
module GreeterHelper
    def formatted_time(time)
        time.strftime("%I:%M%p")
    end
end

app/views/courses/index.html.erb
<form method="GET">
<h2> Search <input type=text name="looking_for"></h2>
<button name="submit" >Search</button>
</form>

<h1>Searching for - <%= @search_term %> </h1>

<table border='1'>
	<tr>
		<th>Image</th>
		<th>Name</th>
		<th>Description</th>
	</tr>
	<% @courses.each do |course| %>
	<tr class= <%= cycle('even','odd') %>>
		<td><img src=<%=course["photoUrl"]%> width=80 height=60></td>
		<td><%= course["name"] %></td>
		<td><%= course["description"] %></td>
	</tr>
	<%end%>
</table>

app/views/greeter/hello.html.erb
<% random_names = ["Dipayan","Nishant","Gopal"] %>
<h1> Greetings , <%= @name %> </h1>
<p>The time now is <%= formatted_time(@time) %> </p>
<p><%= link_to "Google", "https://www.google.com" %></p>
<p><%= link_to "Good Bye" , greeter_goodbye_path  %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFirstApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'default', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>